---
title: "RA Bootcamp Warmup"
subtitle: "Cleaning"
author: "Xihang ZOU"
date: "2024.8.16"
format:
  html:
    toc: true
    toc-depth: 2
    toc-title: "Contents"
    toc-location: left
    number-sections: true
    number-depth: 3
    code-tools:
      toggle: true
      source: false
    code-link: true
    crossrefs-hover: false
    citations-hover: false
    footnotes-hover: false
    citation-location: margin
    reference-location: margin
    df-print: tibble
    theme: default
    embed-resources: true
crossref:
  fig-title: "図"
  tbl-title: "表"
  fig-prefix: "図"
  tbl-prefix: "表"
  chapters: true
execute:
  error: false
  warning: false
  fig.align: "center"
# knitr:
#   opts_chunk:
#     dev: "ragg_png"
editor: source
editor_options:
  chunk_output_type: inline
---

```{r}
#| label: setup
#| include: false

rm(list = ls())
```


### パッケージの読み込み {.unnumbered}

```{r}
#| label: load packages

#pacmanをインストール
if (!require(pacman))  {
  install.packages("pacman")
}

#tidyvreseをロード
pacman::p_load(tidyverse)
```

# Semester Dataの変形

## 生データの読み込み

```{r}
#| label: read data

#csvの読み込み
semester_dummy_1 <- read_csv("semester_data_1.csv")
semester_dummy_2 <- read_csv("semester_data_2.csv")
```

```{r}
#| echo: false

#データを表示
head(semester_dummy_1)
head(semester_dummy_2)
```

## semester_dummy_1.csvの1行目を列名とする

```{r}
#| label: edit column names

#1行目を削除
semester_dummy_1_renamed <- semester_dummy_1[-1, ]
semester_dummy_2_renamed <- semester_dummy_2

#列名を変更
colnames(semester_dummy_1_renamed) <- semester_dummy_1[1, ]
colnames(semester_dummy_2_renamed) <- semester_dummy_1[1, ]
```

```{r}
#| echo: false
head(semester_dummy_1_renamed)
```

## 2つのデータを結合する

```{r}
#| label: merge data

semester_dummy_1_character <- semester_dummy_1_renamed |> 
  mutate(unitid = as.double(unitid), semester = as.double(semester), quarter = as.double(quarter), year = as.double(year), Y = as.double(Y))

semester_dummy_3 <- bind_rows(semester_dummy_1_character, semester_dummy_2_renamed)

```

```{r}
#| echo: false
head(semester_dummy_3)
```

## "Y"列を削除

```{r}
#| label: delete Y

#Y列を除く
semester_dummy_4 <- semester_dummy_3[, -6]
```

```{r}
#| echo: false
head(semester_dummy_4)
```
## semester制が導入された年の列を作成

```{r}
#| label: add yearofsem

semester_dummy_5 <- semester_dummy_4 |> 
  group_by(unitid) |> 
  mutate(
    yearofsem = if_else(all(semester == 1) | all(quarter == 1), NA, 
                        min(year[semester == 1], na.rm = TRUE))
  ) |> 
  ungroup()
```


```{r}
#| echo: false
head(semester_dummy_5)
```

## semester制導入後を示すダミー変数を作成

```{r}
#| label: add after

semester_dummy_6 <- semester_dummy_5 |> 
  group_by(unitid) |> 
  mutate(
    after = if_else(is.na(yearofsem), NA, 
                    if_else(year >= yearofsem, 1, 0))
  ) |> 
  ungroup()
```

```{r}
#| echo: false
head(semester_dummy_6)
```

# Gradrate Dataの整形

# Covariates Dataの整形